### ISSUE TITLE
Waiting for your code.

### ISSUE THREAD

**Issue by qaazii** [wvangansbeke/Sparse-Depth-Completion#1]
Hi, waiting for your cod to release.. Can you tell how many days it will take to complete. Thanks in advance.

**Comment by wvangansbeke** [comment]
Hard to say. I'm waiting on KU Leuven (for licence reasons). I hope it will happen next week.

**Comment by yangkai798** [comment]
will release?

**Comment by liyuxiaoboy** [comment]
mark and follow the progress of this work

**Comment by wvangansbeke** [comment]
Just updated the code.

Kind regards,
Wouter
