### ISSUE TITLE
Confusing Terminologies 

### ISSUE THREAD

**Issue by loayezzat** [wvangansbeke/Sparse-Depth-Completion#11]
Hi 
I'm a student using the project for educational purposes, I just want to understand the difference between Local branch, Global branch and confidence maps, I've searched for them on Google and I've got nothing. 
Thanks.

**Comment by wvangansbeke** [comment]
Hi @loayezzat,

Local branch: consists of a small network (=small receptive field) which looks at the local features.
Global branch: consists of a deep network (large receptive field) which can look at the global features.
Confidence map: Probability map between 0 an 1 which we multiply with the corresponding depth prediction map. This tell you how confident each branch is for each pixel. 

More info can be found in the paper.

Kind regards,
Wouter
