### ISSUE TITLE
test on vlp-16 dataset

### ISSUE THREAD

**Issue by XiaotaoGuo** [wvangansbeke/Sparse-Depth-Completion#12]
Hi,

Recently I've been trying on training on our dataset that is generated from a vlp-16 lidar. Before that, I tried to perform training on reduced lines version of kitti dataset (I manually reduced 3/4 lines) and it works fine and the output looks likes generated on 64-line version roughly. However when I trained on our dataset, the result is not such satisfactory, I can barely recognize the object especially its edge. So it there something I can do such as image augmentation or is it related to our ground truth since it contains some noise especially when there is moving object

**Comment by wvangansbeke** [comment]
Hi @XiaotaoGuo,

That"s actually a hard question to answer. Since I didn't look at that dataset, it will probably need some hyperparameter tuning. Indeed, maybe there is too much noise in the ground truth.

Kind regards,
Wouter
