### ISSUE TITLE
Where is main.py

### ISSUE THREAD

**Issue by ChrGri** [wvangansbeke/Sparse-Depth-Completion#13]
It seems like, that the main.py is missing in your branch.

Regards

**Comment by wvangansbeke** [comment]
Hi @kookaburra88,

Yes indeed. Take a look at the [README](https://github.com/wvangansbeke/Sparse-Depth-Completion/blob/master/README.md). You can still find it [here](https://github.com/wvangansbeke/Sparse-Depth-Completion/tree/99e8986590ee38b0b17c77fb1df3746e7ee08eab) though.

Kind regards
