### ISSUE TITLE
About metrics update

### ISSUE THREAD

**Issue by longyangqi** [wvangansbeke/Sparse-Depth-Completion#14]
Thanks for your code!
I am confused about the metric update method in your validation. (Line 402~404 in main.py)

```
metric.calculate(prediction[:, 0:1], gt)
score.update(metric.get_metric(args.metric), metric.num)
score_1.update(metric.get_metric(args.metric_1), metric.num)
```
why do you use the weight `metric.num` instead of `input.size(0)` ?  
(And I found the result (RMSE) of using `metric.num` is about 30mm lower than the result (RMSE) of using `input.size(0)`  ?)
Thanks!

**Comment by wvangansbeke** [comment]
Hi @longyangqi,

For the correct calculation, you should take into account that the ground truth is semi-dense. This means that we need to keep track of the valid points per image. Take a look at the evaluation script of KITTI to see the detailed calculation of the RMSE for the benchmark.  

Best,
Wouter

**Comment by longyangqi** [comment]
> Hi @longyangqi,
> 
> For the correct calculation, you should take into account that the ground truth is semi-dense. This means that we need to keep track of the valid points per image. Take a look at the evaluation script of KITTI to see the detailed calculation of the RMSE for the benchmark.
> 
> Best,
> Wouter

Thank you for your reply!
Yeah, I did not notice the evaluation script of KITTI.  I have read it now ! 
Your implementation is corresponding to the function `statWeightedMean` in the evaluation script of KITTI `cpp/utils.h`.      Right?   
But the  `eval` function using 'statMean' instead of 'statWeightedMean'  ?
I'm still confused about that.

Thanks!

**Comment by wvangansbeke** [comment]
Hi @longyangqi,

You could be right. My calculation is only an approximation since I calculate the RMSE on the whole batch and not per image as KITTI and I do a weighing dependent on the amount of points. I don't think it matters much to be honest as long as the comparisons are consistent. 

Regards,
Wouter

**Comment by longyangqi** [comment]
I get it.

Thanks a lot!
