### ISSUE TITLE
Dataset Download

### ISSUE THREAD

**Issue by josephdanielchang** [wvangansbeke/Sparse-Depth-Completion#17]
What paths are supposed to be specified when running "source test.sh"? The description says to enter path to dataset and path to ground truth for selection validation files. What exactly is path to dataset because when I look inside test.py, it seems like it is supposed to be path to directory for saving output?

**Comment by wvangansbeke** [comment]
Hi @josephdanielchang,

You are correct. I changed it in the README. 

Best,
Wouter
