### ISSUE TITLE
Training with Confidence for Global and Local Networks

### ISSUE THREAD

**Issue by saikumar96** [wvangansbeke/Sparse-Depth-Completion#18]
From the paper:
"We first train both parts of the framework individually and use a pretrained ERFNet on Cityscapes [22] for our global network."
I was wondering how global and local networks are trained whether with or without confidence maps and how is the final end to end training done, with these pre-trained sub-networks

**Comment by wvangansbeke** [comment]
Hi @saikumar96,

Yes you are right. Both parts can be trained individually and later everything can be trained together. When you use skip connections between the local and global network, it's not that important. Differences are negligable. This version can be trained end-to-end without problem.

Best, 
Wouter

**Comment by LiangliangGuo** [comment]
Hi @wvangansbeke 

What I want to know is whether you first train global net and local net separately, and the combine then for end to end?

**Comment by wvangansbeke** [comment]
Hi @LiangliangGuo,

I initially did it like you described.
Now in the latest version, I simply trained it end-to-end. It should give you the same numbers.

Best,
Wouter

**Comment by LiangliangGuo** [comment]
@wvangansbeke Thank you very much for your kind answer!!!
