### ISSUE TITLE
About dataset

### ISSUE THREAD

**Issue by why-freedom** [wvangansbeke/Sparse-Depth-Completion#21]
Do I need to download all avg-kitti/raw_data datasets for testing purposes only? There are more than 200。Too much

**Comment by wvangansbeke** [comment]
Hi @why-freedom,

The KITTI dataset is indeed quite large (> 100 GB).  So make sure you have enough space. If you want optimal performance you have to train on as much data as possible. Deep learning is very data hungry after all.

Best,
Wouter
