### ISSUE TITLE
What is "input_type" in args???

### ISSUE THREAD

**Issue by KhizarAziz** [wvangansbeke/Sparse-Depth-Completion#22]
Hi there, thanks for the code... 
Can you kindly elaborate what is this "input_type" argument is for?

Sorry for a noob question, actually i am just learning this deep learning... and getting my hands dirty on your code.....

**Comment by wvangansbeke** [comment]
Hi @khizerawan,

It was meant to include rgb or not. I will have to check it again, but the default arguments should be fine.

Best,
Wouter
