### ISSUE TITLE
About normalize the input

### ISSUE THREAD

**Issue by mzy97** [wvangansbeke/Sparse-Depth-Completion#26]
In https://github.com/wvangansbeke/Sparse-Depth-Completion/issues/5#issue-458380549 this issue, dataloader have the code to normalize depth and RGB to 0-1, but I can't find the normalize code in the current dataloader version, which way (normalize or not) is better?

**Comment by wvangansbeke** [comment]
Hi @mzy97,

It would surprise that normalization makes a huge difference for the end result after training (on so many labels). Networks nowadays are more than capable enough to learn this constant. In short, don't spend too much time on it :). Hope it helps.

Best,
Wouter
