### ISSUE TITLE
Erased my system data completely

### ISSUE THREAD

**Issue by Rajat-Mehta** [wvangansbeke/Sparse-Depth-Completion#27]
I ran ```source download_raw_files.sh``` script in my system(ubuntu 18 with python 3.7.5) and after running for some time I saw that my system data got erased completely. And now I am not able to use my system, whole data including my home folder has been deleted.

Does it have any link with your download_raw_files.sh script?  I see that there are some "rm -f" commands in your script. 

Thanks

**Comment by wvangansbeke** [comment]
Hmm that shouldn't happen. It works for me though. You probably were in a different directory then. My best advice is to download the files yourself though KITTI's website. I will also modify the readme, so this does not happen again. 

Wouter

**Comment by Rajat-Mehta** [comment]
I was in /Downloads directory when I ran this script, I followed instructions given in your readme.
