### ISSUE TITLE
Problem with metric calculation

### ISSUE THREAD

**Issue by TruongKhang** [wvangansbeke/Sparse-Depth-Completion#29]
Hi, thank you for sharing your great work.

I've been looking through your implementation of the evaluation metric. In class Metrics of file benchmark_metrics.py, I found this line `self.num = valid_mask.sum().item()`. I think it might be wrong because this is the number of non-zero pixels. I think this variable should be the batch_size and equal to 1 because you use this variable when computing the average value of metrics in file main.py as follows:
`score.update(metric.get_metric(args.metric), metric.num)
 score_1.update(metric.get_metric(args.metric_1), metric.num)`.

Am I understanding correctly? Please correct me if I have misunderstanding something.

Best,
Khang Truong.

**Comment by wvangansbeke** [comment]
Hi @TruongKhang,

This could be the case, however I used the KITTI scripts to compute the final metrics. The ones I provide in the code are really close to ones of KITTI actually. Feel free to change it but it doesn't matter much.

Best,
Wouter
