### ISSUE TITLE
Pregenerated Depthmaps somewhere?

### ISSUE THREAD

**Issue by soulslicer** [wvangansbeke/Sparse-Depth-Completion#30]
Hi, do you have these high resolution depthmaps saved somewhere i can download? I could run your network to generate it, but i just need to depthmaps

**Comment by wvangansbeke** [comment]
Hi @soulslicer,

Do you need the predictions on the test set? If so, you can find them [here](https://drive.google.com/drive/folders/1U7dvH4sC85KRVuV19fRpaMzJjE-m3D9x?usp=sharing) as is mentioned in the README.

Best,
Wouter
