### ISSUE TITLE
Testing with other KITTI sequences or other data

### ISSUE THREAD

**Issue by MrMixit** [wvangansbeke/Sparse-Depth-Completion#32]
Hi!

We have been working with a KITTI sequence that does not seem to have projected Lidar scans available. If I understand the code correctly, you do not use the raw Lidar scans at all, right? So we would have to project the Lidar scans to images if we want to do something like that?

Also, we have a handheld Lidar (Intel Realsense L515) that can capture both RGB images and depth images, and we were thinking of trying to feed your code with this data. Do you know if the images (rgb and depth) have to be of the same size for the code to work?

Best,
Adam

**Comment by wvangansbeke** [comment]
Hi @MrMixit,

Thank you for your interest!

Indeed, the LiDAR scans need to be projected to 2D in order to apply this method. 
Ideally, the RGB image and sparse depth map are aligned perfectly (KITTI already provides this). Keep in mind that the feature maps for the two modalities are fused (e.g. concatenated) after all. 

If you want to do the projection yourself, have a look [here](https://github.com/nianticlabs/monodepth2/blob/master/kitti_utils.py#L46). 

Hope this helps.

**Comment by MrMixit** [comment]
Thank you, I will check that out!

**Comment by MrMixit** [comment]
Hi again! 

I realized I had one more question on the same topic. If we have data (projected depth images and images), how do we feed it to Sparse-Depth-Completion? Is there anything more we need as input, and which module/script should we run to get depth completed images as output?

Best, Adam

**Comment by wvangansbeke** [comment]
Hi @MrMixit,

If you simply want to test a pretrained model, have a look at `test.py` and `test.sh`. The dataloading is probably going to be different, so normally you only need to change that part. The network outputs the completed depth map. You should be able to save it sowewhere. However, if your data is different from KITTI, I would advise you train on you own dataset first if you have ground truth available.

Hope this helps.

**Comment by MrMixit** [comment]
Thank you, this is great! We plan on using it both on KITTI and on our own data, and as you say training another model will probably be a great idea for the latter. 

For KITTI data we would like to use the pretrained model to get output in the form of depth images for a specific data sequence, that is not part of the data that the test.sh or test.py are loading from by default. Would it be sufficient to put this data (images+projected lidar images) in the correct folder that the dataloading is loading from, or will we need something more?

**Comment by wvangansbeke** [comment]
You should be able to augment the image paths (see [this line](https://github.com/wvangansbeke/Sparse-Depth-Completion/blob/fa31dca6041d2bebd66ea55b259bf054d571571d/Datasets/Kitti_loader.py#L139)) with your own dataset. However, you need to check the resolution of your input, it might be different from the one in KITTI. I specifically made `test.py` to handle KITTI's resolution.

**Comment by MrMixit** [comment]
Thank you, we will look at doing that then!

**Comment by abhishekk06** [comment]
@wvangansbeke 

how do I train the model in a new dataset?
