### ISSUE TITLE
How did you render the results shown in video? 

### ISSUE THREAD

**Issue by 619862306** [wvangansbeke/Sparse-Depth-Completion#33]

**Comment by wvangansbeke** [comment]
Hi @619862306,
 
I like this type of visualization a lot, but it is not included in this repo. Check out #23 for a detailed answer. You basically need to make a point cloud using the predicted depth and intrinsics matrix, change the position of the camera (shift the y-axis for example) to obtain a 3D effect and then map it to the image plane. 

Hope this helps.

**Comment by wvangansbeke** [comment]
Feel free to ask more questions if it's still not clear. I will close this for now.
