### ISSUE TITLE
Size of image from an imported folder

### ISSUE THREAD

**Issue by SebsBarbas** [wvangansbeke/Sparse-Depth-Completion#34]
Hi!
I have been tweaking around your code in order to gain some insight of how it works and I have ran into this question. Why in test.py you want the loaded images to have a specific input size (lines 101-104):

```python
raw_pil = Image.open(raw_path)
gt_path = os.path.join(gt)
gt_pil = Image.open(gt)
assert raw_pil.size == (1216, 352)
```

But this is not required for the training in main.py.
Afterwards I see you crop the images in both codes until they are 1216 x 256 (as stated in your paper) so I do not understand why would it be so important to make sure that the loaded image in test.py has a specific input format (1216, 352) which is not even the one from the KITTI dataset download files (1226 x 370). Is there any insight I am missing?

**Comment by wvangansbeke** [comment]
Hi @SebsBarbas,

I specifically made `test.py` to get predictions on the KITTI test set. If you go to the `depth_selection/test_depth_completion_anonymous` or `depth_selection/val_selection_cropped` folder, you will see that KITTI cropped the images to 1216 x 352.

Hope this helps.

**Comment by SebsBarbas** [comment]
Hi,
Yes perfect. Thanks for the quick response and congrats on your magnificent work.
Best,
Sebastián

**Comment by wvangansbeke** [comment]
Thanks!
Good luck with your research.

**Comment by zshn25** [comment]
Hi @wvangansbeke,

I'm sorry. I am a bit confused about the input image sizes. All I want to do is to densify KITTI ground truth images and save them. I don't want to crop them. So, should I resize the input to `1216 x 352` before giving it to the model? What do you think?

Thank you

**Comment by wvangansbeke** [comment]
Hi @zshn25,

Since there is no ground truth available at the top of the images for KITTI, I cropped this part. This was useful during training (memory consumption) and you won't be able to learn much anyway. So the predictions in that region won't be useful I guess. I don't think it is possible to accurately densify the top of the image anyway. You might try it without cropping (1216x352) and check how much the RMSE drops. Otherwise consider cropping.

Hope this helps.

**Comment by zshn25** [comment]
Thank you @wvangansbeke

**Comment by wvangansbeke** [comment]
You can maybe also use a mask to make clear that the pixels at the top are not valid (the depth values can be incorrect here).
