### ISSUE TITLE
try to run /Download/download_raw_files.sh

### ISSUE THREAD

**Issue by rightchose** [wvangansbeke/Sparse-Depth-Completion#39]

**Comment by rightchose** [comment]
I donwload `data_depth_annotated.zip`,`data_depth_selection.zip`,`data_depth_velodyne.zip`. And I put them under `./Data`. Then I try to run the `download_raw_files.sh`, but I get the message 
 `mv: cannot stat ‘2011_09_26_drive_0001_syncproj_depth’: No such file or directory`.
I think it is caused by `mv $i'proj_depth' $date'/'$name`.

**Comment by wvangansbeke** [comment]
Hi @rightchose,

That script worked for me but I think it is better to follow the official KITTI website and download all the files from there. They also provide scripts for this. I would also advise you to keep the original dataset structure of KITTI so you can use the same dataset for other tasks (e.g. depth prediction) and not only for depth completion. It is maybe a little bit more work now, but better in the long run.

**Comment by rightchose** [comment]
Thank you for answer and advise, I'll download the raw data from official website.
