### ISSUE TITLE
Can't run the code

### ISSUE THREAD

**Issue by mjtian** [wvangansbeke/Sparse-Depth-Completion#41]
Hi, I want to reproduce your results. I have followed the procedures in the readme, However, I found several places that are not specific enough. Would you mind share those details about

1. Do you unpack the downloaded Dataset (Data_Depth_Annotated. Zip, Data_Depth_Velodyne. Zip, Depth_Selection. Zip), put it in the `Data` folder, and then do preprocess part as you wrote? 

2. The contents and structure of the `Saved` folder, e.g. what's the three path in the following command,`sourceTest/test.sh /path/to/directory_with_saved_model/ $num_samples /path/to/dataset/ /path/to/directory_with_ground_truth_for_selected_validation_files/`

I would appreciate it if you could reply.

**Comment by wvangansbeke** [comment]
Hi @mjtian,

- Yes you need to unpack it and preprocess it. You can always make your own dataset file. The RGB images and sparse depth maps just need to match during the data loading.  
- The arguments are needed for the test.sh script. Please have look at it to better understand it. You need the path to the directory of the trained model, the validation set directory and dataset location.

**Comment by wvangansbeke** [comment]
If you still have problems, let me know. Closing this for now.

**Comment by abhishekk06** [comment]
Hi @mjtian / @wvangansbeke 

Can you please share the steps that I can follow to reproduce the result. Maybe I can convert it to shell script so that it can be pretty much automated.
