### ISSUE TITLE
Confusions about dataset

### ISSUE THREAD

**Issue by ITBoy-China** [wvangansbeke/Sparse-Depth-Completion#42]
Hi,
I'm reading your paper and trying to reproduce your work.But there are some confusions on me.I have downloaded data_depth_annotated.zip,data_depth_velodyne.zip and data_depth_selection.zip.I have followed the instruction of kitti website and unziped data_depth_annotated.zip and data_depth_velodyne.zip into the same folder.My confusions are as follows.

1. Files in data_depth_annotated.zip are ground truth of depth and files in data_depth_velodyne.zip are raw depth,is my understanding right?
2. Files in data_depth_selection.zip are prepared for us to evaluate model,is my understanding right?
3. I only find RGB images in data_depth_selection.zip.If I want to use RGB images for guidence,where are the corresponding RGB images in the two zip files,data_depth_annotated.zip and data_depth_velodyne.zip.
4. What's the meaning of embedding1,embedding2,embedding3,embedding4?In other words,embedding from ERFNet as input of hourglass network,why?

I would appreciate it if you could help me with above confusions.

**Comment by wvangansbeke** [comment]
Hi @ITBoy-China,

Thank you for you interest in our work!
- You should be able to find the the projected depth and the annotations on [KITTI's website](http://www.cvlibs.net/datasets/kitti/eval_depth.php?benchmark=depth_completion). You can find the corresponding RGB images [here](http://www.cvlibs.net/datasets/kitti/raw_data.php).
-  Yes. `data_depth_selection.zip` can be used to evaluate your model.
- You need to download the raw RGB images and make sure that you match them with the corresponding depth maps during the dataloading.
- Embedding1-4` are skip connections between the global network and the local network or skip connections between the hourglass networks (in the local net). This improves the results considerably.

**Comment by abhishekk06** [comment]
Hi @wvangansbeke @ITBoy-China,

For some reason, this link is not working for me to download the dataset. Is it modified?


[Data]$  wget 'http://www.cvlibs.net/download.php?file=data_depth_annotated.zip'
--2021-03-25 22:40:23--  http://www.cvlibs.net/download.php?file=data_depth_annotated.zip
Resolving www.cvlibs.net (www.cvlibs.net)... 85.214.204.21
Connecting to www.cvlibs.net (www.cvlibs.net)|85.214.204.21|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘download.php?file=data_depth_annotated.zip’

    [  <=>                                                                                                                                                             ] 1,091       1.74KB/s   in 0.6s

2021-03-25 22:40:25 (1.74 KB/s) - ‘download.php?file=data_depth_annotated.zip’ saved [1091]


Please note that it is downloading some junk file which I am just not able to unzip. I hit the same issue when I try to use the script provided in the repo to download the dataset. Am I doing something wrong?

**Comment by ITBoy-China** [comment]
> Hi @ITBoy-China,
> 
> Thank you for you interest in our work!
> 
> * You should be able to find the the projected depth and the annotations on [KITTI's website](http://www.cvlibs.net/datasets/kitti/eval_depth.php?benchmark=depth_completion). You can find the corresponding RGB images [here](http://www.cvlibs.net/datasets/kitti/raw_data.php).
> * Yes. `data_depth_selection.zip` can be used to evaluate your model.
> * You need to download the raw RGB images and make sure that you match them with the corresponding depth maps during the dataloading.
> * Embedding1-4` are skip connections between the global network and the local network or skip connections between the hourglass networks (in the local net). This improves the results considerably.

 @wvangansbeke Thanks for your patient reply. I'll try it by myself. If I still have some problems , I will discuss with you . Thanks again.

**Comment by ITBoy-China** [comment]
> Hi @wvangansbeke @ITBoy-China,
> 
> For some reason, this link is not working for me to download the dataset. Is it modified?
> 
> [Data]$ wget 'http://www.cvlibs.net/download.php?file=data_depth_annotated.zip'
> --2021-03-25 22:40:23-- http://www.cvlibs.net/download.php?file=data_depth_annotated.zip
> Resolving [www.cvlibs.net](http://www.cvlibs.net) ([www.cvlibs.net](http://www.cvlibs.net))... 85.214.204.21
> Connecting to [www.cvlibs.net](http://www.cvlibs.net) ([www.cvlibs.net)|85.214.204.21|:80](http://www.cvlibs.net)%7C85.214.204.21%7C:80)... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: unspecified [text/html]
> Saving to: ‘download.php?file=data_depth_annotated.zip’
> 
> ```
> [  <=>                                                                                                                                                             ] 1,091       1.74KB/s   in 0.6s
> ```
> 
> 2021-03-25 22:40:25 (1.74 KB/s) - ‘download.php?file=data_depth_annotated.zip’ saved [1091]
> 
> Please note that it is downloading some junk file which I am just not able to unzip. I hit the same issue when I try to use the script provided in the repo to download the dataset. Am I doing something wrong?

Hi @abhishekk06 ,I had encountered the same problem before. Then I used Chrome to download. Just like this
![image](https://user-images.githubusercontent.com/44388327/112576949-53c52180-8e2e-11eb-9d3c-d6227b556bee.png)

It seems that you should send your email to get the real download path. Then they will send the real download path to your email.

**Comment by abhishekk06** [comment]
Yes did the same. Thank you very much for the help.
