### ISSUE TITLE
Dataset Prepare

### ISSUE THREAD

**Issue by YuhsiHu** [wvangansbeke/Sparse-Depth-Completion#44]
Hi, thank you for your great work!
I download data_depth_selection.zip, data_depth_velodyne.zip and data_depth_annotated.zip from Kitti website and unzip them. Howerver,  where can I download the camera images I need and what structure should I build before data preprocessing in README.md?
Thank you!

**Comment by Lin-Luo** [comment]
Hi, I have face the same question, How did you solve it?  and where can I download the images? Thank you very much!

**Comment by wvangansbeke** [comment]
Just follow the instructions on the official KITTI website.
