### ISSUE TITLE
The problem about RGB dataset

### ISSUE THREAD

**Issue by WeixuWang** [wvangansbeke/Sparse-Depth-Completion#45]
I have downloaded raw datasets from the Kitti dataset, but I don't know how to split in into train and val folders, could you tell me?

**Comment by wvangansbeke** [comment]
You need to check the sequence names for the depth completion task on KITTIs website. Start by downloading the necessary files and write a script so you can train on the correct split. You'll see that this split differs from other tasks on KITTI.
