### ISSUE TITLE
RGB image for training and validation

### ISSUE THREAD

**Issue by XiaotaoGuo** [wvangansbeke/Sparse-Depth-Completion#6]
Hi,

I am wondering do I need to download the whole raw data from kitti official website? It seems that there is no way to just download RGB images(I've downloaded the depth and lidar part from depth completion in kitti benchmark). Thanks!

**Comment by wvangansbeke** [comment]
Hi @XiaotaoGuo,

I think it is better to download the whole dataset. I know it includes some files you don't need (like the LiDAR files) but it is the safest way. BTW, if you understand some bash you can do something like the code underneath to download all the files automatically. You can probably find better scripts on KITTI, but this should work: 

```
cd '/train/folder or /validation/folder'
train_files=($(ls -d */ | sed 's#/##'))
echo ${files[@]}
Download_files ${train_files[@]}

function Download_files(){
	files=($@)
	for i in ${files[@]}; do
		if [ ${i:(-3)} != "zip" ]; then
				date="${i:0:10}"
				name=$(basename $i /)
				shortname=$name'.zip'
				fullname=$(basename $i _sync)'/'$name'.zip'
				echo 'shortname: '$shortname
		else
			echo 'Something went wrong. Input array names are probably not correct! Check this manually!'
		fi
		echo "Downloading: "$shortname
		wget 'https://s3.eu-central-1.amazonaws.com/avg-kitti/raw_data/'$fullname
		unzip -o $shortname
		rm -f $shortname
		mv $i'proj_depth' $date'/'$name
		rm -rf $name
	done
}
```
Kind regards,
Wouter

**Comment by XiaotaoGuo** [comment]
Thank you! Btw, once I downloaded the dataset, all I need to do is move the image_02 and image_03 folders to /data_depth_velodyne/rgb/. Is that right?

**Comment by wvangansbeke** [comment]
Hi @XiaotaoGuo,

I put the RGB files in a separate folder with the same subdirectories. I doesn't really matter of course. Just make sure you get the correct files. 

FYI, my file structure looks like this:
```
|--depth selection
|-- Depth
       |-- train
              |--date
                   |--sequence1
                   | ...
       |--validation
|--RGB
       |--train
       |--validation
```
Kind regards,
Wouter

**Comment by XiaotaoGuo** [comment]
Thanks for the explanation!
