### ISSUE TITLE
RGB input type 

### ISSUE THREAD

**Issue by OmarMGhanem** [wvangansbeke/Sparse-Depth-Completion#7]
Hi , 
I wonder if you can supply me with a detailed data set structure  
I've ran the code using input_type as depth ,but while trying to run  it as RGB i get out of indexing error I think due fail in data set structure  

Regards ,
Omar .

**Comment by wvangansbeke** [comment]
Hi @OmarMGhanem,

Ok I see. I did not really focus on this part since you can do this in so many ways. 

I basically put the RGB files in a separate folder with the same subdirectories as the original Lidar files. Checkout `Datasets/Kitti_dataloader.py`, but my file structure looks like this:

```
|--depth selection
|-- Depth
       |-- train
              |--date
                   |--sequence1
                   | ...
       |--validation
|--RGB
       |--train
              |--date
       |--validation
```
Kind regards,
Wouter

**Comment by OmarMGhanem** [comment]
I think I solved data set structure 
but now I get new error

![Capture](https://user-images.githubusercontent.com/29588310/61190465-d9299200-a69c-11e9-9676-e7115c8676b1.PNG)


If you can help me, I'll be thankful :)

**Comment by wvangansbeke** [comment]
Hi @OmarMGhanem,

Yeah something seems wrong. The amount of files for validation does not seem to be correct. Can you share your dataset structure? Maybe I can spot the difference with respect to mine. Also, make sure that there are no RGB images in the validation directory for the Depth directory. 

Best,
Wouter

**Comment by OmarMGhanem** [comment]
Hi @wvangansbeke  Here is a Screenshot from my DATA dir  
![image](https://user-images.githubusercontent.com/29588310/61209239-7adecc80-a6f9-11e9-9dd9-85d60fd7be3f.png)
I tried to change Rgb file many time but this structure was the only one to be read in the main code 

Regards,
Omar

**Comment by wvangansbeke** [comment]
Hi @OmarMGhanem,

The amount of validation files should be 6852 for both the depth directory and the Rgb directory. Can you maybe play with the keywords to the dataloading step more precise. I will also take a look at my file structure.

Best,
Wouter

**Comment by OmarMGhanem** [comment]
Hi @wvangansbeke  

After some time playing with the data I think I fixed this issue and encountered another one :D 

![image](https://user-images.githubusercontent.com/29588310/61315765-c5e30780-a7ff-11e9-9714-6abeef1339dc.png)

I've tried to change subset size , but all what's happening is the file name at the end change at the OSerror

Regards,
Omar

**Comment by wvangansbeke** [comment]
Hi @OmarMGhanem,

The problem seems to be that it tries to import a binary file (*.bin). This means that there is still something wrong in the dataloading part (we don't train on those files after all). Maybe verify some files in de dataloader to identify the issue.

Best,
Wouter
