### ISSUE TITLE
colormap for visualizing the result

### ISSUE THREAD

**Issue by XiaotaoGuo** [wvangansbeke/Sparse-Depth-Completion#8]
Hi,

May I ask which colormap you use to visualize your result? I checked all cmap options of matplotlib and seen none looks like yours. Thanks!

**Comment by wvangansbeke** [comment]
Hi @XiaotaoGuo,

I think your looking for the colormaps: _plasma_ and _magma_. I used the former to visualize the depth maps and the latter to visualize the confidence maps.

Best,
Wouter

**Comment by XiaotaoGuo** [comment]
Thanks for the explanation!
